"""
Django settings for gmart_project project.

Generated by 'django-admin startproject' using Django 3.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
import platform
from pathlib import Path
import requests
import django_heroku

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


#----------------------------#
#          SECURITY          #
#----------------------------#

EnvPlatform = platform.system()
print('--- Platform ---')
print(platform.system())
# Get Credentials from OS Environment Variables

if (EnvPlatform=="Windows"):

    # AWS IAM Credentials
    AWS_ACCESS_KEY_ID = os.getenv('GMT_AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('GMT_AWS_SECRET_ACCESS_KEY')

    # Django App Credentials
    SECRET_KEY = os.getenv('GMT_DJANGO_APP_SECRET_KEY')

    # Postgres Database Credentials
    DB_ENGINE = os.getenv('GMT_POSTGRES_ENGINE')
    DB_NAME = os.getenv('GMT_POSTGRES_NAME')
    DB_USERNAME = os.getenv('GMT_POSTGRES_USERNAME')
    DB_PASSWORD = os.getenv('GMT_POSTGRES_PASSWORD')
    DB_HOST = os.getenv('GMT_POSTGRES_HOST')
    DB_PORT = os.getenv('GMT_POSTGRES_PORT')
    print("Got all dem enviros!")

elif (EnvPlatform=="Linux"):

    # AWS IAM Credentials
    AWS_ACCESS_KEY_ID = os.environ['GMT_AWS_ACCESS_KEY_ID']
    AWS_SECRET_ACCESS_KEY = os.environ['GMT_AWS_SECRET_ACCESS_KEY']

    # Django App Credentials
    SECRET_KEY = os.environ['GMT_DJANGO_APP_SECRET_KEY']

    # Postgres Database Credentials
    DB_ENGINE = os.environ['GMT_POSTGRES_ENGINE']
    DB_NAME = os.environ['GMT_POSTGRES_NAME']
    DB_USERNAME = os.environ['GMT_POSTGRES_USERNAME']
    DB_PASSWORD = os.environ['GMT_POSTGRES_PASSWORD']
    DB_HOST = os.environ['GMT_POSTGRES_HOST']
    DB_PORT = os.environ['GMT_POSTGRES_PORT']

# SECURITY WARNING: don't run with debug turned on in production!
if (EnvPlatform=="Linux"):
    DEBUG = False
else:
    DEBUG = True

# Host Security Whitelist
ALLOWED_HOSTS = ['gmart.us-west-2.elasticbeanstalk.com', 'localhost']

# Grab the AWS Elastic Beanstalk Private IP and dynamically add it to the allowed hosts

EC2_PRIVATE_IP = None
try:
    security_token = requests.put(
        'http://169.254.169.254/latest/api/token',
        headers={'X-aws-ec2-metadata-token-ttl-seconds': '60'}).text

    EC2_PRIVATE_IP = requests.get(
        'http://169.254.169.254/latest/meta-data/local-ipv4',
        headers={'X-aws-ec2-metadata-token': security_token},
        timeout=0.01).text
except requests.exceptions.RequestException:
    pass

if EC2_PRIVATE_IP:
    ALLOWED_HOSTS.append(EC2_PRIVATE_IP)



# S3 Storage for photos
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
AWS_STORAGE_BUCKET_NAME = 'gmart-s3bucket'
AWS_S3_REGION_NAME = 'us-east-1'

AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_FILE_OVERWRITE = True
AWS_DEFAULT_ACL = None
AWS_S3_VERIFY = True



#----------------------------#
#    Application Settings    #
#----------------------------#


# Application definition
INSTALLED_APPS = [
    # Main Django App
    'gmart_app.apps.GmartAppConfig',

    # Django Core Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.humanize',
    'django.contrib.staticfiles',

    # Additional Apps
    'users.apps.UsersConfig',
    'crispy_forms',
    'crispy_bootstrap4',
    'django.contrib.postgres',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gmart_project.urls'

# Added a custom processor called get_departments_list to prvode access to departments from all templates 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gmart_project.wsgi.application'

DATABASES = {
   'default': {
       'ENGINE': DB_ENGINE,
       'NAME': DB_NAME,
       'USER': DB_USERNAME,
       'PASSWORD': DB_PASSWORD,
       'HOST': DB_HOST,
       'PORT': DB_PORT,
   }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = 'static'

# GR Change the default location of where media & image files are located
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'gmart-home'
LOGIN_URL = 'login'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

django_heroku.settings(locals())