# Generated by Django 4.1.3 on 2023-06-03 17:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Created', models.DateTimeField(auto_now_add=True)),
                ('Order_Date', models.DateTimeField()),
                ('Order_Ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Description', models.TextField()),
                ('Product_Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Product_Quantity', models.IntegerField()),
                ('Product_Highlights', models.TextField()),
                ('Product_Details', models.TextField()),
                ('Product_Image_Primary', models.ImageField(default='no_product.jpg', upload_to='product_images')),
                ('Product_Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmart_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderItem_Quantity', models.IntegerField(default=1)),
                ('OrderItem_Order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmart_app.order')),
                ('OrderItem_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmart_app.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='Order_Product',
            field=models.ManyToManyField(through='gmart_app.OrderItem', to='gmart_app.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='Order_User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
