# Generated by Django 3.1.5 on 2021-01-09 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Department_Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=100)),
                ('Product_Description', models.TextField()),
                ('Product_Price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('Product_Quantity', models.IntegerField()),
                ('Product_Highlights', models.TextField()),
                ('Prodcut_Details', models.TextField()),
                ('Product_Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmart_app.department')),
            ],
        ),
    ]
