# Generated by Django 3.1.5 on 2021-01-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmart_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Prodcut_Details',
            new_name='Product_Details',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_Image_Primary',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='Department_Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
