# Generated by Django 3.1.5 on 2021-01-10 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmart_app', '0003_auto_20210110_1405'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_Image_Primary',
            field=models.ImageField(default='no_product.jpg', upload_to='product_images'),
        ),
    ]
