# Generated by Django 3.1.5 on 2021-01-23 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gmart_app', '0004_auto_20210110_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderItem_Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gmart_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_Created', models.DateTimeField(auto_now_add=True)),
                ('Order_Date', models.DateTimeField()),
                ('Order_Ordered', models.BooleanField(default=False)),
                ('Order_Product', models.ManyToManyField(to='gmart_app.OrderItem')),
                ('Order_User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
