# Generated by Django 3.1.5 on 2021-01-23 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmart_app', '0005_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='OrderItem_Quantity',
            field=models.IntegerField(default=1),
        ),
    ]
