# Generated by Django 3.1.5 on 2021-01-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gmart_app', '0006_orderitem_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='OrderItem_Order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gmart_app.order'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='Order_Product',
            field=models.ManyToManyField(through='gmart_app.OrderItem', to='gmart_app.Product'),
        ),
    ]
